### PR TITLE
Async impl example

### PR DESCRIPTION
**Pull request by dhollman**
- uses future to hold both the async result and exception, allowing us to get rid of expected
- moves the bounds checking to the mapping where it's more appropriate (it's a pedantic thing for a 1D mdspan, but it makes the example more idiomatic)

(Sorry this took so long; also sorry I haven't incorporated changes you made since I started playing with this)

### CODE REVIEW

**Comment by dhollman** [comment]
(Okay, now I merged in your changes. I can also go to your 2x3 version also if you want)

**Comment by dhollman** [comment]
Okay generalized to multidimensional to match where your example is now. This is so cool! Thanks for involving me!

**Comment by griswaldbrooks** [comment]
I brought a 6 pack of beer for the robot to check and am going to attempt a love demo, so, you're call.

**Comment by griswaldbrooks** [comment]
This looks really clean. It's really cool to see the layout bounds checking code, and it never occurred to me that the reference type can be a value type. I really like using expected and will probably refactor that later.

**Pull request merged**
